# Generated by Django 2.2.5 on 2020-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_customer_vehical'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vehical',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Vehical',
        ),
    ]
