# Generated by Django 2.2.5 on 2020-06-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200627_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CUser',
        ),
    ]
