# Generated by Django 2.2.5 on 2020-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_trandingcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trandingcourse',
            name='rating',
            field=models.CharField(choices=[('1', 'one'), ('2', 'three'), ('3', 'two'), ('4', 'four'), ('5', 'five')], max_length=1),
        ),
    ]
