# Generated by Django 2.2.5 on 2020-07-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20200701_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandingcourse',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trandingcourse',
            name='rating',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1),
        ),
    ]
