# Generated by Django 2.2.5 on 2020-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20200701_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=1)),
                ('course_img', models.ImageField(upload_to='media/')),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
