# Generated by Django 2.2.5 on 2020-07-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_webcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebCourse',
        ),
    ]
