# Generated by Django 2.2.5 on 2020-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_webcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandingcourse',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcourse',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
