# Generated by Django 2.2.5 on 2020-07-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20200701_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainingmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
